// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjkfyhvqpvdktifzcgjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqa2Z5aHZxcHZka3RpZnpjZ2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODA2NzUsImV4cCI6MjA2MDA1NjY3NX0.hEod4O63tjvYueer26x4Qri4JngqoGbMt4WYwcMB4rU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);